title: "jetbundle"
description: "Engineering with principles of physics, mathematics and computation."
url: "https://jetbundle.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/og-image.svg

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
